// Generated by gencpp from file pruebas/numsteps.msg
// DO NOT EDIT!


#ifndef PRUEBAS_MESSAGE_NUMSTEPS_H
#define PRUEBAS_MESSAGE_NUMSTEPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pruebas
{
template <class ContainerAllocator>
struct numsteps_
{
  typedef numsteps_<ContainerAllocator> Type;

  numsteps_()
    : az(0)
    , al(0)  {
    }
  numsteps_(const ContainerAllocator& _alloc)
    : az(0)
    , al(0)  {
  (void)_alloc;
    }



   typedef int16_t _az_type;
  _az_type az;

   typedef int16_t _al_type;
  _al_type al;





  typedef boost::shared_ptr< ::pruebas::numsteps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pruebas::numsteps_<ContainerAllocator> const> ConstPtr;

}; // struct numsteps_

typedef ::pruebas::numsteps_<std::allocator<void> > numsteps;

typedef boost::shared_ptr< ::pruebas::numsteps > numstepsPtr;
typedef boost::shared_ptr< ::pruebas::numsteps const> numstepsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pruebas::numsteps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pruebas::numsteps_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pruebas

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'pruebas': ['/home/pi/seguidorsolar_ws/src/pruebas/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pruebas::numsteps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pruebas::numsteps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pruebas::numsteps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pruebas::numsteps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pruebas::numsteps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pruebas::numsteps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pruebas::numsteps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e80bebf4b25dc28d9ae73b0b269a9fdb";
  }

  static const char* value(const ::pruebas::numsteps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe80bebf4b25dc28dULL;
  static const uint64_t static_value2 = 0x9ae73b0b269a9fdbULL;
};

template<class ContainerAllocator>
struct DataType< ::pruebas::numsteps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pruebas/numsteps";
  }

  static const char* value(const ::pruebas::numsteps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pruebas::numsteps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 az\n\
int16 al\n\
";
  }

  static const char* value(const ::pruebas::numsteps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pruebas::numsteps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.az);
      stream.next(m.al);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct numsteps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pruebas::numsteps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pruebas::numsteps_<ContainerAllocator>& v)
  {
    s << indent << "az: ";
    Printer<int16_t>::stream(s, indent + "  ", v.az);
    s << indent << "al: ";
    Printer<int16_t>::stream(s, indent + "  ", v.al);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRUEBAS_MESSAGE_NUMSTEPS_H
